baseURL = "https://khiproteam.github.io/khipro/"
languageCode = "bn"
title = "ক্ষিপ্র কিবোর্ড"
defaultContentLanguage = "bn"

[params]
description = "দ্রুততম বাংলা কিবোর্ড"
keywords = "বাংলা কিবোর্ড, ক্ষিপ্র কিবোর্ড, বাংলা টাইপিং, Bengali keyboard, Khipro, Bangla typing"
author = "KhiproTeam"

canonifyURLs = true
relativeURLs = false

disableKinds = ["sitemap"]

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 4
ordered = false

[outputs]
home = ["HTML"]
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]
page = ["HTML"]
