baseURL = "/"
languageCode = "bn"
title = "ক্ষিপ্র কিবোর্ড"
defaultContentLanguage = "bn"

[params]
description = "দ্রুততম বাংলা কিবোর্ড"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 4
ordered = false

# Enable 404 page output
[outputs]
home = ["HTML"]
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]
page = ["HTML"]
